Repository FusionComputingLab/freegsnke, pull requests merged in 2025-08, with the labels that each got.

#25 Error catch in inverse solver
  freegsnke/inverse.py
Labels: bug, ready-for-final-tests

#27 Updating reference list
  README.md
Labels: documentation, ready-for-final-tests

#31 Coil activation
  examples/example05 - evolutive_forward_solve.ipynb
  freegsnke/circuit_eq_metal.py
  freegsnke/linear_solve.py
  freegsnke/nonlinear_solve.py
  freegsnke/normal_modes.py
  freegsnke/simplified_solve.py
  freegsnke/tests/test_dynamics.py
Labels: enhancement, ready-for-final-tests
